spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  allowed:
    origins: http://localhost:3000

jwt:
  secret: asdfghjklcfgvhbfdknlfdsjghdfskjldshgvdcgvhfkjnlasdfghjklcfgvhbfdknlfdsjghdfskjldshgvdcgvhfkjnlasdfghjklcfgvhbfdknlfdsjghdfskjldshgvdcgvhfkjnl