spring:
  datasource:
    url: jdbc:postgresql://nozomi.proxy.rlwy.net:19661/railway
    username: postgres
    password: svYWWZOFmPevNRpQzhatlZiKphLdXCeb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  allowed:
    origins: http://localhost:3000

jwt:
  secret: asdfghjklcfgvhbfdknlfdsjghdfskjldshgvdcgvhfkjnlasdfghjklcfgvhbfdknlfdsjghdfskjldshgvdcgvhfkjnlasdfghjklcfgvhbfdknlfdsjghdfskjldshgvdcgvhfkjnl