name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven Build
        run: ./mvnw -B package -DskipTests



  deploy_dev:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - run: |
          echo "1) DEV deployment başladı..."
          echo "Railway dev env deploy edilir."


  deploy_staging:
    needs: deploy_dev
    runs-on: ubuntu-latest
    environment:
      name: staging
      # burada GitHub UI-də approval tələbi olacaq
    steps:
      - run: |
          echo "2) STAGING deployment başladı..."
          echo "Railway staging env deploy edilir."


  deploy_prod:
    needs: deploy_staging
    runs-on: ubuntu-latest
    environment:
      name: production
      # yenə manual approval tələb edəcək
    steps:
      - run: |
          echo "3) PROD deployment başladı..."
          echo "Railway production env deploy edilir."
